//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forestry.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ForestryStormsOutbound")]
        public string ContentApplicationName {
            get {
                return ((string)(this["ContentApplicationName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxx")]
        public string ContentUserId {
            get {
                return ((string)(this["ContentUserId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Energy-Delivery/ManagedWorkOrder/api/")]
        public string ManagedWorkOrderUri {
            get {
                return ((string)(this["ManagedWorkOrderUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/enterprise/messaging/v2/queues/")]
        public string MqApiUri {
            get {
                return ((string)(this["MqApiUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/work-requests/{workRequestId}/ifexception-conditions")]
        public string ManagedWorkOrderApiResourse_IfExceptionConditions {
            get {
                return ((string)(this["ManagedWorkOrderApiResourse_IfExceptionConditions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/work-requests/{workRequestId}/milestone-requirements")]
        public string ManagedWorkOrderApiResourse_MilestoneRequirements {
            get {
                return ((string)(this["ManagedWorkOrderApiResourse_MilestoneRequirements"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/work-requests/{workRequestId}")]
        public string ManagedWorkOrderApiResourse_WorkRequest {
            get {
                return ((string)(this["ManagedWorkOrderApiResourse_WorkRequest"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://xxxxx/enterprise/service-management")]
        public string RemedyUriHost {
            get {
                return ((string)(this["RemedyUriHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/v1/incidents/")]
        public string RemedyUri {
            get {
                return ((string)(this["RemedyUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/work-requests/{workRequestId}/trackings")]
        public string ManagedWorkOrderApiResourse_WorkRequestTrackings {
            get {
                return ((string)(this["ManagedWorkOrderApiResourse_WorkRequestTrackings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxx")]
        public string ManagedWorkOrderUriHost {
            get {
                return ((string)(this["ManagedWorkOrderUriHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/work-requests/{workRequestId}/milestone-requirements/{id}")]
        public string ManagedWorkOrderApiResourse_MilestoneRequirement {
            get {
                return ((string)(this["ManagedWorkOrderApiResourse_MilestoneRequirement"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEV")]
        public string Env {
            get {
                return ((string)(this["Env"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxx")]
        public string ManagedWorkOrderUriCredentials {
            get {
                return ((string)(this["ManagedWorkOrderUriCredentials"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://xxxxx")]
        public string MqApiUriHost {
            get {
                return ((string)(this["MqApiUriHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=xxxxx; password=xxxxx; user id=xxxxx")]
        public string STORMS_EntityFrameworkConnectionString {
            get {
                return ((string)(this["STORMS_EntityFrameworkConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxx")]
        public string RemedyUriCredentials {
            get {
                return ((string)(this["RemedyUriCredentials"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxxxx")]
        public string MqApiUriCredentials {
            get {
                return ((string)(this["MqApiUriCredentials"]));
            }
        }
    }
}
