// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Address
    {
        /// <summary>
        /// Initializes a new instance of the Address class.
        /// </summary>
        public Address() { }

        /// <summary>
        /// Initializes a new instance of the Address class.
        /// </summary>
        public Address(string organization = default(string), string building = default(string), string floor = default(string), string streetNumber = default(string), string streetPrefix = default(string), string streetName = default(string), string streetType = default(string), string streetSuffix = default(string), string unitId = default(string), string unitType = default(string), string city = default(string), string county = default(string), string state = default(string), string zip = default(string), string extraInfo = default(string), string freeFormat = default(string), string cityCode = default(string))
        {
            Organization = organization;
            Building = building;
            Floor = floor;
            StreetNumber = streetNumber;
            StreetPrefix = streetPrefix;
            StreetName = streetName;
            StreetType = streetType;
            StreetSuffix = streetSuffix;
            UnitId = unitId;
            UnitType = unitType;
            City = city;
            County = county;
            State = state;
            Zip = zip;
            ExtraInfo = extraInfo;
            FreeFormat = freeFormat;
            CityCode = cityCode;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "organization")]
        public string Organization { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "building")]
        public string Building { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "floor")]
        public string Floor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetNumber")]
        public string StreetNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetPrefix")]
        public string StreetPrefix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetName")]
        public string StreetName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetType")]
        public string StreetType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "streetSuffix")]
        public string StreetSuffix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitId")]
        public string UnitId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitType")]
        public string UnitType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "county")]
        public string County { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zip")]
        public string Zip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extraInfo")]
        public string ExtraInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freeFormat")]
        public string FreeFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cityCode")]
        public string CityCode { get; set; }

    }
}
