// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class AssociatedParty
    {
        /// <summary>
        /// Initializes a new instance of the AssociatedParty class.
        /// </summary>
        public AssociatedParty() { }

        /// <summary>
        /// Initializes a new instance of the AssociatedParty class.
        /// </summary>
        public AssociatedParty(string url = default(string), long? workRequestId = default(long?), long? seq = default(long?), Address address = default(Address), Phones phones = default(Phones), string entityType = default(string))
        {
            Url = url;
            WorkRequestId = workRequestId;
            Seq = seq;
            Address = address;
            Phones = phones;
            EntityType = entityType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seq")]
        public long? Seq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public Address Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phones")]
        public Phones Phones { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entityType")]
        public string EntityType { get; set; }

    }
}
