// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class CU
    {
        /// <summary>
        /// Initializes a new instance of the CU class.
        /// </summary>
        public CU() { }

        /// <summary>
        /// Initializes a new instance of the CU class.
        /// </summary>
        public CU(string workRequestId = default(string), string unitAction = default(string), string account = default(string), string unitCode = default(string), string muId = default(string), string designNumber = default(string), string pointNumber = default(string), string pointSpanNumber = default(string), string usage = default(string), string onOff = default(string), string equipNumber = default(string), string supplyMethod = default(string), string quantity = default(string), string district = default(string), string restorationFlag = default(string), string materialSubExistsFlag = default(string), long? workpacketId = default(long?), UnitDetail unitDetail = default(UnitDetail), IList<CUFacilityAttribute> cuFacilityAttributes = default(IList<CUFacilityAttribute>), IList<LaborDetail> laborDetails = default(IList<LaborDetail>))
        {
            WorkRequestId = workRequestId;
            UnitAction = unitAction;
            Account = account;
            UnitCode = unitCode;
            MuId = muId;
            DesignNumber = designNumber;
            PointNumber = pointNumber;
            PointSpanNumber = pointSpanNumber;
            Usage = usage;
            OnOff = onOff;
            EquipNumber = equipNumber;
            SupplyMethod = supplyMethod;
            Quantity = quantity;
            District = district;
            RestorationFlag = restorationFlag;
            MaterialSubExistsFlag = materialSubExistsFlag;
            WorkpacketId = workpacketId;
            UnitDetail = unitDetail;
            CuFacilityAttributes = cuFacilityAttributes;
            LaborDetails = laborDetails;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public string WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitAction")]
        public string UnitAction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public string Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitCode")]
        public string UnitCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "muId")]
        public string MuId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designNumber")]
        public string DesignNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpanNumber")]
        public string PointSpanNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public string Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onOff")]
        public string OnOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipNumber")]
        public string EquipNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplyMethod")]
        public string SupplyMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "restorationFlag")]
        public string RestorationFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "materialSubExistsFlag")]
        public string MaterialSubExistsFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workpacketId")]
        public long? WorkpacketId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitDetail")]
        public UnitDetail UnitDetail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuFacilityAttributes")]
        public IList<CUFacilityAttribute> CuFacilityAttributes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "laborDetails")]
        public IList<LaborDetail> LaborDetails { get; set; }

    }
}
