// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class CUAsb
    {
        /// <summary>
        /// Initializes a new instance of the CUAsb class.
        /// </summary>
        public CUAsb() { }

        /// <summary>
        /// Initializes a new instance of the CUAsb class.
        /// </summary>
        public CUAsb(long? workRequestId = default(long?), string unitAction = default(string), string account = default(string), string unitCode = default(string), string muid = default(string), string pointNumber = default(string), string pointSpanNumber = default(string), string usage = default(string), string onOff = default(string), string equipNumber = default(string), string supplyMethod = default(string), string quantity = default(string), string crewClass = default(string), string district = default(string), string workOrderCode = default(string), double? facilityLaborHours = default(double?), string restorationFlag = default(string), string facilityCode = default(string), DateTime? timeStampLastChanged = default(DateTime?), string orderNumber = default(string), int? asbuiltDesignNumber = default(int?), long? cuId = default(long?), long? workpacketId = default(long?), double? constructionLaborHours = default(double?), double? nonConstructionLaborHours = default(double?), double? constructionLaborAmount = default(double?), double? nonConstructionLaborAmount = default(double?), string budgetItemCode = default(string), IList<CUFacilityAttribute> cuFacilityAttributes = default(IList<CUFacilityAttribute>))
        {
            WorkRequestId = workRequestId;
            UnitAction = unitAction;
            Account = account;
            UnitCode = unitCode;
            Muid = muid;
            PointNumber = pointNumber;
            PointSpanNumber = pointSpanNumber;
            Usage = usage;
            OnOff = onOff;
            EquipNumber = equipNumber;
            SupplyMethod = supplyMethod;
            Quantity = quantity;
            CrewClass = crewClass;
            District = district;
            WorkOrderCode = workOrderCode;
            FacilityLaborHours = facilityLaborHours;
            RestorationFlag = restorationFlag;
            FacilityCode = facilityCode;
            TimeStampLastChanged = timeStampLastChanged;
            OrderNumber = orderNumber;
            AsbuiltDesignNumber = asbuiltDesignNumber;
            CuId = cuId;
            WorkpacketId = workpacketId;
            ConstructionLaborHours = constructionLaborHours;
            NonConstructionLaborHours = nonConstructionLaborHours;
            ConstructionLaborAmount = constructionLaborAmount;
            NonConstructionLaborAmount = nonConstructionLaborAmount;
            BudgetItemCode = budgetItemCode;
            CuFacilityAttributes = cuFacilityAttributes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitAction")]
        public string UnitAction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public string Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitCode")]
        public string UnitCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "muid")]
        public string Muid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpanNumber")]
        public string PointSpanNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public string Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onOff")]
        public string OnOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipNumber")]
        public string EquipNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplyMethod")]
        public string SupplyMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public string Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewClass")]
        public string CrewClass { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workOrderCode")]
        public string WorkOrderCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityLaborHours")]
        public double? FacilityLaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "restorationFlag")]
        public string RestorationFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityCode")]
        public string FacilityCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStampLastChanged")]
        public DateTime? TimeStampLastChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asbuiltDesignNumber")]
        public int? AsbuiltDesignNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuId")]
        public long? CuId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workpacketId")]
        public long? WorkpacketId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "constructionLaborHours")]
        public double? ConstructionLaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nonConstructionLaborHours")]
        public double? NonConstructionLaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "constructionLaborAmount")]
        public double? ConstructionLaborAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nonConstructionLaborAmount")]
        public double? NonConstructionLaborAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "budgetItemCode")]
        public string BudgetItemCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuFacilityAttributes")]
        public IList<CUFacilityAttribute> CuFacilityAttributes { get; set; }

    }
}
