// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class CUFacilityAttribute
    {
        /// <summary>
        /// Initializes a new instance of the CUFacilityAttribute class.
        /// </summary>
        public CUFacilityAttribute() { }

        /// <summary>
        /// Initializes a new instance of the CUFacilityAttribute class.
        /// </summary>
        public CUFacilityAttribute(long? workRequestId = default(long?), string cuName = default(string), string attributeName = default(string), string pointNumber = default(string), string pointSpan = default(string), string usage = default(string), string supplyMethod = default(string), string account = default(string), string action = default(string), string onOff = default(string), string equip = default(string), string muId = default(string), long? idSeq = default(long?), string value = default(string), string facility = default(string), string requiredFlag = default(string), string district = default(string), long? idcu = default(long?))
        {
            WorkRequestId = workRequestId;
            CuName = cuName;
            AttributeName = attributeName;
            PointNumber = pointNumber;
            PointSpan = pointSpan;
            Usage = usage;
            SupplyMethod = supplyMethod;
            Account = account;
            Action = action;
            OnOff = onOff;
            Equip = equip;
            MuId = muId;
            IdSeq = idSeq;
            Value = value;
            Facility = facility;
            RequiredFlag = requiredFlag;
            District = district;
            Idcu = idcu;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuName")]
        public string CuName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attributeName")]
        public string AttributeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpan")]
        public string PointSpan { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public string Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplyMethod")]
        public string SupplyMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public string Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onOff")]
        public string OnOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equip")]
        public string Equip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "muId")]
        public string MuId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idSeq")]
        public long? IdSeq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facility")]
        public string Facility { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredFlag")]
        public string RequiredFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idcu")]
        public long? Idcu { get; set; }

    }
}
