// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class CuJobCodePointTransformer
    {
        /// <summary>
        /// Initializes a new instance of the CuJobCodePointTransformer class.
        /// </summary>
        public CuJobCodePointTransformer() { }

        /// <summary>
        /// Initializes a new instance of the CuJobCodePointTransformer class.
        /// </summary>
        public CuJobCodePointTransformer(long? workRequestId = default(long?), IList<CuJobCode> cuJobCodes = default(IList<CuJobCode>))
        {
            WorkRequestId = workRequestId;
            CuJobCodes = cuJobCodes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuJobCodes")]
        public IList<CuJobCode> CuJobCodes { get; set; }

    }
}
