// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Customer
    {
        /// <summary>
        /// Initializes a new instance of the Customer class.
        /// </summary>
        public Customer() { }

        /// <summary>
        /// Initializes a new instance of the Customer class.
        /// </summary>
        public Customer(string url = default(string), long? workRequestId = default(long?), Address address = default(Address), Phones phones = default(Phones), string name = default(string), string customerType = default(string), string ssn = default(string), string effectiveMoveInDate = default(string), string dogCode = default(string), string customerId = default(string), string premiseId = default(string))
        {
            Url = url;
            WorkRequestId = workRequestId;
            Address = address;
            Phones = phones;
            Name = name;
            CustomerType = customerType;
            Ssn = ssn;
            EffectiveMoveInDate = effectiveMoveInDate;
            DogCode = dogCode;
            CustomerId = customerId;
            PremiseId = premiseId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public Address Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phones")]
        public Phones Phones { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerType")]
        public string CustomerType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssn")]
        public string Ssn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectiveMoveInDate")]
        public string EffectiveMoveInDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dogCode")]
        public string DogCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "premiseId")]
        public string PremiseId { get; set; }

    }
}
