// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class CUStructure
    {
        /// <summary>
        /// Initializes a new instance of the CUStructure class.
        /// </summary>
        public CUStructure() { }

        /// <summary>
        /// Initializes a new instance of the CUStructure class.
        /// </summary>
        public CUStructure(string cuCode = default(string), string materialItemNumber = default(string), double? allowance = default(double?), double? quantityItem = default(double?), string drawingSeqCode = default(string), DateTime? lastChangedDateTime = default(DateTime?), MaterialItem materialItem = default(MaterialItem))
        {
            CuCode = cuCode;
            MaterialItemNumber = materialItemNumber;
            Allowance = allowance;
            QuantityItem = quantityItem;
            DrawingSeqCode = drawingSeqCode;
            LastChangedDateTime = lastChangedDateTime;
            MaterialItem = materialItem;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuCode")]
        public string CuCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "materialItemNumber")]
        public string MaterialItemNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowance")]
        public double? Allowance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantityItem")]
        public double? QuantityItem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "drawingSeqCode")]
        public string DrawingSeqCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastChangedDateTime")]
        public DateTime? LastChangedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "materialItem")]
        public MaterialItem MaterialItem { get; set; }

    }
}
