// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class CuTransformer
    {
        /// <summary>
        /// Initializes a new instance of the CuTransformer class.
        /// </summary>
        public CuTransformer() { }

        /// <summary>
        /// Initializes a new instance of the CuTransformer class.
        /// </summary>
        public CuTransformer(long? workRequestId = default(long?), ExtDesignKey key = default(ExtDesignKey), string pointNumber = default(string), string pointSpanNumber = default(string), int? quanity = default(int?), UnitDetail unitDetail = default(UnitDetail))
        {
            WorkRequestId = workRequestId;
            Key = key;
            PointNumber = pointNumber;
            PointSpanNumber = pointSpanNumber;
            Quanity = quanity;
            UnitDetail = unitDetail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public ExtDesignKey Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpanNumber")]
        public string PointSpanNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quanity")]
        public int? Quanity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitDetail")]
        public UnitDetail UnitDetail { get; set; }

    }
}
