// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Damage
    {
        /// <summary>
        /// Initializes a new instance of the Damage class.
        /// </summary>
        public Damage() { }

        /// <summary>
        /// Initializes a new instance of the Damage class.
        /// </summary>
        public Damage(long? workRequest = default(long?), string employeeId = default(string), DateTime? currentDate = default(DateTime?), string arrivalTime = default(string), string damagedAddress = default(string), string damagedCity = default(string), string damagedState = default(string), string damagedZip = default(string), string damagedPhone = default(string), string damagedParty = default(string), string responsibleParty = default(string), string responsibleOperator = default(string), string responsibleAddress = default(string), string responsibleCity = default(string), string responsibleState = default(string), string responsibleZip = default(string), string responsiblePhone = default(string), string damageLiabilityAdmit = default(string), string damageLiability = default(string), string chargedParty = default(string), string locateRequest = default(string), string locateTicket = default(string), string locateCompany = default(string), string locateArea = default(string), string locateMarkCorrect = default(string), string damageGasLeak = default(string), string damageOrificeSize = default(string), string damagePressure = default(string), string damageDuration = default(string), string nature = default(string), string cause = default(string), string evidenceAvailable = default(string), string pictureCollected = default(string), string evidenceCollected = default(string), string damageInformation = default(string), string damageStored = default(string), string damageLocation = default(string), string responsibleSupervisor = default(string), string responsiblePartyName = default(string), string damageTime = default(string), string damagedPartyName = default(string), int? dispatchedWorkRequest = default(int?))
        {
            WorkRequest = workRequest;
            EmployeeId = employeeId;
            CurrentDate = currentDate;
            ArrivalTime = arrivalTime;
            DamagedAddress = damagedAddress;
            DamagedCity = damagedCity;
            DamagedState = damagedState;
            DamagedZip = damagedZip;
            DamagedPhone = damagedPhone;
            DamagedParty = damagedParty;
            ResponsibleParty = responsibleParty;
            ResponsibleOperator = responsibleOperator;
            ResponsibleAddress = responsibleAddress;
            ResponsibleCity = responsibleCity;
            ResponsibleState = responsibleState;
            ResponsibleZip = responsibleZip;
            ResponsiblePhone = responsiblePhone;
            DamageLiabilityAdmit = damageLiabilityAdmit;
            DamageLiability = damageLiability;
            ChargedParty = chargedParty;
            LocateRequest = locateRequest;
            LocateTicket = locateTicket;
            LocateCompany = locateCompany;
            LocateArea = locateArea;
            LocateMarkCorrect = locateMarkCorrect;
            DamageGasLeak = damageGasLeak;
            DamageOrificeSize = damageOrificeSize;
            DamagePressure = damagePressure;
            DamageDuration = damageDuration;
            Nature = nature;
            Cause = cause;
            EvidenceAvailable = evidenceAvailable;
            PictureCollected = pictureCollected;
            EvidenceCollected = evidenceCollected;
            DamageInformation = damageInformation;
            DamageStored = damageStored;
            DamageLocation = damageLocation;
            ResponsibleSupervisor = responsibleSupervisor;
            ResponsiblePartyName = responsiblePartyName;
            DamageTime = damageTime;
            DamagedPartyName = damagedPartyName;
            DispatchedWorkRequest = dispatchedWorkRequest;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequest")]
        public long? WorkRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employeeId")]
        public string EmployeeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currentDate")]
        public DateTime? CurrentDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "arrivalTime")]
        public string ArrivalTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedAddress")]
        public string DamagedAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedCity")]
        public string DamagedCity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedState")]
        public string DamagedState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedZip")]
        public string DamagedZip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedPhone")]
        public string DamagedPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedParty")]
        public string DamagedParty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleParty")]
        public string ResponsibleParty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleOperator")]
        public string ResponsibleOperator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleAddress")]
        public string ResponsibleAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleCity")]
        public string ResponsibleCity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleState")]
        public string ResponsibleState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleZip")]
        public string ResponsibleZip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsiblePhone")]
        public string ResponsiblePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageLiabilityAdmit")]
        public string DamageLiabilityAdmit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageLiability")]
        public string DamageLiability { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chargedParty")]
        public string ChargedParty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locateRequest")]
        public string LocateRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locateTicket")]
        public string LocateTicket { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locateCompany")]
        public string LocateCompany { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locateArea")]
        public string LocateArea { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locateMarkCorrect")]
        public string LocateMarkCorrect { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageGasLeak")]
        public string DamageGasLeak { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageOrificeSize")]
        public string DamageOrificeSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagePressure")]
        public string DamagePressure { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageDuration")]
        public string DamageDuration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nature")]
        public string Nature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cause")]
        public string Cause { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "evidenceAvailable")]
        public string EvidenceAvailable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pictureCollected")]
        public string PictureCollected { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "evidenceCollected")]
        public string EvidenceCollected { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageInformation")]
        public string DamageInformation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageStored")]
        public string DamageStored { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageLocation")]
        public string DamageLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsibleSupervisor")]
        public string ResponsibleSupervisor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responsiblePartyName")]
        public string ResponsiblePartyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damageTime")]
        public string DamageTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "damagedPartyName")]
        public string DamagedPartyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dispatchedWorkRequest")]
        public int? DispatchedWorkRequest { get; set; }

    }
}
