// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Design
    {
        /// <summary>
        /// Initializes a new instance of the Design class.
        /// </summary>
        public Design() { }

        /// <summary>
        /// Initializes a new instance of the Design class.
        /// </summary>
        public Design(string url = default(string), string district = default(string), long? workRequestId = default(long?), string designNumber = default(string), string designDescription = default(string), bool? flagPreferred = default(bool?), bool? flagComplete = default(bool?), bool? flagExtDesign = default(bool?), string idOper = default(string), IList<Point> points = default(IList<Point>))
        {
            Url = url;
            District = district;
            WorkRequestId = workRequestId;
            DesignNumber = designNumber;
            DesignDescription = designDescription;
            FlagPreferred = flagPreferred;
            FlagComplete = flagComplete;
            FlagExtDesign = flagExtDesign;
            IdOper = idOper;
            Points = points;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designNumber")]
        public string DesignNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designDescription")]
        public string DesignDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flagPreferred")]
        public bool? FlagPreferred { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flagComplete")]
        public bool? FlagComplete { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flagExtDesign")]
        public bool? FlagExtDesign { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idOper")]
        public string IdOper { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "points")]
        public IList<Point> Points { get; set; }

    }
}
