// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class DocumentBlob
    {
        /// <summary>
        /// Initializes a new instance of the DocumentBlob class.
        /// </summary>
        public DocumentBlob() { }

        /// <summary>
        /// Initializes a new instance of the DocumentBlob class.
        /// </summary>
        public DocumentBlob(string blobId = default(string), byte[] blob = default(byte[]), int? uncompressedFileSize = default(int?), string compressionType = default(string), DateTime? reapDate = default(DateTime?))
        {
            BlobId = blobId;
            Blob = blob;
            UncompressedFileSize = uncompressedFileSize;
            CompressionType = compressionType;
            ReapDate = reapDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blobId")]
        public string BlobId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blob")]
        public byte[] Blob { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uncompressedFileSize")]
        public int? UncompressedFileSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "compressionType")]
        public string CompressionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reapDate")]
        public DateTime? ReapDate { get; set; }

    }
}
