// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Document
    {
        /// <summary>
        /// Initializes a new instance of the Document class.
        /// </summary>
        public Document() { }

        /// <summary>
        /// Initializes a new instance of the Document class.
        /// </summary>
        public Document(string url = default(string), long? workRequestId = default(long?), long? seqId = default(long?), string documentDescription = default(string), string documentName = default(string), long? workPacketId = default(long?), string mobileFlag = default(string), string blobId = default(string), DateTime? updateDate = default(DateTime?), string tpDocument = default(string), string path = default(string), DocumentBlob documentBlob = default(DocumentBlob))
        {
            Url = url;
            WorkRequestId = workRequestId;
            SeqId = seqId;
            DocumentDescription = documentDescription;
            DocumentName = documentName;
            WorkPacketId = workPacketId;
            MobileFlag = mobileFlag;
            BlobId = blobId;
            UpdateDate = updateDate;
            TpDocument = tpDocument;
            Path = path;
            DocumentBlob = documentBlob;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seqId")]
        public long? SeqId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentDescription")]
        public string DocumentDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentName")]
        public string DocumentName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workPacketId")]
        public long? WorkPacketId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mobileFlag")]
        public string MobileFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blobId")]
        public string BlobId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updateDate")]
        public DateTime? UpdateDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tpDocument")]
        public string TpDocument { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentBlob")]
        public DocumentBlob DocumentBlob { get; set; }

    }
}
