// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Equipment
    {
        /// <summary>
        /// Initializes a new instance of the Equipment class.
        /// </summary>
        public Equipment() { }

        /// <summary>
        /// Initializes a new instance of the Equipment class.
        /// </summary>
        public Equipment(string url = default(string), string equipmentId = default(string), string equipmentDescription = default(string), string customerType = default(string), bool? active = default(bool?))
        {
            Url = url;
            EquipmentId = equipmentId;
            EquipmentDescription = equipmentDescription;
            CustomerType = customerType;
            Active = active;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipmentId")]
        public string EquipmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipmentDescription")]
        public string EquipmentDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerType")]
        public string CustomerType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

    }
}
