// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class ExceptionCondition
    {
        /// <summary>
        /// Initializes a new instance of the ExceptionCondition class.
        /// </summary>
        public ExceptionCondition() { }

        /// <summary>
        /// Initializes a new instance of the ExceptionCondition class.
        /// </summary>
        public ExceptionCondition(string url = default(string), string district = default(string), long? workRequestId = default(long?), string conditionDescription = default(string), string operatorId = default(string), long? conditionCode = default(long?), DateTime? exceptionConditionTimeStamp = default(DateTime?), long? sequenceNumber = default(long?))
        {
            Url = url;
            District = district;
            WorkRequestId = workRequestId;
            ConditionDescription = conditionDescription;
            OperatorId = operatorId;
            ConditionCode = conditionCode;
            ExceptionConditionTimeStamp = exceptionConditionTimeStamp;
            SequenceNumber = sequenceNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conditionDescription")]
        public string ConditionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conditionCode")]
        public long? ConditionCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exceptionConditionTimeStamp")]
        public DateTime? ExceptionConditionTimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sequenceNumber")]
        public long? SequenceNumber { get; set; }

    }
}
