// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class ExtraDetails
    {
        /// <summary>
        /// Initializes a new instance of the ExtraDetails class.
        /// </summary>
        public ExtraDetails() { }

        /// <summary>
        /// Initializes a new instance of the ExtraDetails class.
        /// </summary>
        public ExtraDetails(string url = default(string), long? workRequestId = default(long?), string district = default(string), string complexFlag = default(string), string subdivisionName = default(string), string lotNo = default(string), string dogCode = default(string), string mapNoId = default(string), string feederId = default(string), string phaseCode = default(string), string feeder2Id = default(string), string phase2Code = default(string), string serviceSizeCode = default(string), string cssMeterPhs = default(string), string serviceVoltageCode = default(string), string customerTypeCode = default(string), string designRequiredDate = default(string), string designerJobElectric = default(string), string mainOrderNumber = default(string), string fieldAlert = default(string), string equipmentId = default(string), string utilityType = default(string), string designerJobGas = default(string), string customerWantDateTime = default(string), string trsQuarter = default(string), string trsSection = default(string), string trsTown = default(string), string trsDirection = default(string), string trsRange = default(string), string constructionType = default(string), string onOffMain = default(string), string buildingType = default(string), string pre1978Construction = default(string), string mainToLotLineFootage = default(string), string pbiAreaNo = default(string), string publicBuilding = default(string), string branchService = default(string), string existingServiceFln = default(string), string trailerParkName = default(string), string systemPressure = default(string))
        {
            Url = url;
            WorkRequestId = workRequestId;
            District = district;
            ComplexFlag = complexFlag;
            SubdivisionName = subdivisionName;
            LotNo = lotNo;
            DogCode = dogCode;
            MapNoId = mapNoId;
            FeederId = feederId;
            PhaseCode = phaseCode;
            Feeder2Id = feeder2Id;
            Phase2Code = phase2Code;
            ServiceSizeCode = serviceSizeCode;
            CssMeterPhs = cssMeterPhs;
            ServiceVoltageCode = serviceVoltageCode;
            CustomerTypeCode = customerTypeCode;
            DesignRequiredDate = designRequiredDate;
            DesignerJobElectric = designerJobElectric;
            MainOrderNumber = mainOrderNumber;
            FieldAlert = fieldAlert;
            EquipmentId = equipmentId;
            UtilityType = utilityType;
            DesignerJobGas = designerJobGas;
            CustomerWantDateTime = customerWantDateTime;
            TrsQuarter = trsQuarter;
            TrsSection = trsSection;
            TrsTown = trsTown;
            TrsDirection = trsDirection;
            TrsRange = trsRange;
            ConstructionType = constructionType;
            OnOffMain = onOffMain;
            BuildingType = buildingType;
            Pre1978Construction = pre1978Construction;
            MainToLotLineFootage = mainToLotLineFootage;
            PbiAreaNo = pbiAreaNo;
            PublicBuilding = publicBuilding;
            BranchService = branchService;
            ExistingServiceFln = existingServiceFln;
            TrailerParkName = trailerParkName;
            SystemPressure = systemPressure;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "complexFlag")]
        public string ComplexFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subdivisionName")]
        public string SubdivisionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lotNo")]
        public string LotNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dogCode")]
        public string DogCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mapNoId")]
        public string MapNoId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "feederId")]
        public string FeederId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phaseCode")]
        public string PhaseCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "feeder2Id")]
        public string Feeder2Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phase2Code")]
        public string Phase2Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceSizeCode")]
        public string ServiceSizeCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cssMeterPhs")]
        public string CssMeterPhs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceVoltageCode")]
        public string ServiceVoltageCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerTypeCode")]
        public string CustomerTypeCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designRequiredDate")]
        public string DesignRequiredDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designerJobElectric")]
        public string DesignerJobElectric { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainOrderNumber")]
        public string MainOrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldAlert")]
        public string FieldAlert { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipmentId")]
        public string EquipmentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "utilityType")]
        public string UtilityType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designerJobGas")]
        public string DesignerJobGas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerWantDateTime")]
        public string CustomerWantDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trsQuarter")]
        public string TrsQuarter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trsSection")]
        public string TrsSection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trsTown")]
        public string TrsTown { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trsDirection")]
        public string TrsDirection { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trsRange")]
        public string TrsRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "constructionType")]
        public string ConstructionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "onOffMain")]
        public string OnOffMain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildingType")]
        public string BuildingType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pre1978Construction")]
        public string Pre1978Construction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainToLotLineFootage")]
        public string MainToLotLineFootage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pbiAreaNo")]
        public string PbiAreaNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publicBuilding")]
        public string PublicBuilding { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branchService")]
        public string BranchService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "existingServiceFln")]
        public string ExistingServiceFln { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trailerParkName")]
        public string TrailerParkName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemPressure")]
        public string SystemPressure { get; set; }

    }
}
