// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Facility
    {
        /// <summary>
        /// Initializes a new instance of the Facility class.
        /// </summary>
        public Facility() { }

        /// <summary>
        /// Initializes a new instance of the Facility class.
        /// </summary>
        public Facility(string facilityName = default(string), string facilityDescription = default(string), string flagActive = default(string), string flagCollectedByQty = default(string), DateTime? lastChanged = default(DateTime?), string tpFacility = default(string))
        {
            FacilityName = facilityName;
            FacilityDescription = facilityDescription;
            FlagActive = flagActive;
            FlagCollectedByQty = flagCollectedByQty;
            LastChanged = lastChanged;
            TpFacility = tpFacility;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityName")]
        public string FacilityName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityDescription")]
        public string FacilityDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flagActive")]
        public string FlagActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flagCollectedByQty")]
        public string FlagCollectedByQty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastChanged")]
        public DateTime? LastChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tpFacility")]
        public string TpFacility { get; set; }

    }
}
