// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class GasLoadDetail
    {
        /// <summary>
        /// Initializes a new instance of the GasLoadDetail class.
        /// </summary>
        public GasLoadDetail() { }

        /// <summary>
        /// Initializes a new instance of the GasLoadDetail class.
        /// </summary>
        public GasLoadDetail(string url = default(string), string district = default(string), long? workRequestId = default(long?), string customerType = default(string), string deliveryPressureProposed = default(string), string equipmentType = default(string), string deliveryPressureExisting = default(string), double? connectLoadQuantity = default(double?), double? connectLoadIncQuantity = default(double?), double? totalEstDemandQuantity = default(double?), string commentsDescription = default(string))
        {
            Url = url;
            District = district;
            WorkRequestId = workRequestId;
            CustomerType = customerType;
            DeliveryPressureProposed = deliveryPressureProposed;
            EquipmentType = equipmentType;
            DeliveryPressureExisting = deliveryPressureExisting;
            ConnectLoadQuantity = connectLoadQuantity;
            ConnectLoadIncQuantity = connectLoadIncQuantity;
            TotalEstDemandQuantity = totalEstDemandQuantity;
            CommentsDescription = commentsDescription;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerType")]
        public string CustomerType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deliveryPressureProposed")]
        public string DeliveryPressureProposed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipmentType")]
        public string EquipmentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deliveryPressureExisting")]
        public string DeliveryPressureExisting { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connectLoadQuantity")]
        public double? ConnectLoadQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connectLoadIncQuantity")]
        public double? ConnectLoadIncQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalEstDemandQuantity")]
        public double? TotalEstDemandQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commentsDescription")]
        public string CommentsDescription { get; set; }

    }
}
