// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Geo
    {
        /// <summary>
        /// Initializes a new instance of the Geo class.
        /// </summary>
        public Geo() { }

        /// <summary>
        /// Initializes a new instance of the Geo class.
        /// </summary>
        public Geo(string area = default(string), string dist = default(string), string xCoordinate = default(string), string yCoordinate = default(string), string zone = default(string))
        {
            Area = area;
            Dist = dist;
            XCoordinate = xCoordinate;
            YCoordinate = yCoordinate;
            Zone = zone;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "area")]
        public string Area { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dist")]
        public string Dist { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xCoordinate")]
        public string XCoordinate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "yCoordinate")]
        public string YCoordinate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zone")]
        public string Zone { get; set; }

    }
}
