// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class IFExtDsgnFacAtt
    {
        /// <summary>
        /// Initializes a new instance of the IFExtDsgnFacAtt class.
        /// </summary>
        public IFExtDsgnFacAtt() { }

        /// <summary>
        /// Initializes a new instance of the IFExtDsgnFacAtt class.
        /// </summary>
        public IFExtDsgnFacAtt(long? facilityNumber = default(long?), long? sequenceCode = default(long?), string facilityValueText = default(string), string attributeCode = default(string), long? externalDesignSequence = default(long?), DateTime? externalDesignTimeStamp = default(DateTime?), string operatorId = default(string), string errorFlag = default(string), long? errorRunSequence = default(long?))
        {
            FacilityNumber = facilityNumber;
            SequenceCode = sequenceCode;
            FacilityValueText = facilityValueText;
            AttributeCode = attributeCode;
            ExternalDesignSequence = externalDesignSequence;
            ExternalDesignTimeStamp = externalDesignTimeStamp;
            OperatorId = operatorId;
            ErrorFlag = errorFlag;
            ErrorRunSequence = errorRunSequence;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityNumber")]
        public long? FacilityNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sequenceCode")]
        public long? SequenceCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityValueText")]
        public string FacilityValueText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attributeCode")]
        public string AttributeCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalDesignSequence")]
        public long? ExternalDesignSequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalDesignTimeStamp")]
        public DateTime? ExternalDesignTimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorFlag")]
        public string ErrorFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorRunSequence")]
        public long? ErrorRunSequence { get; set; }

    }
}
