// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class IFExtDsgnPoint
    {
        /// <summary>
        /// Initializes a new instance of the IFExtDsgnPoint class.
        /// </summary>
        public IFExtDsgnPoint() { }

        /// <summary>
        /// Initializes a new instance of the IFExtDsgnPoint class.
        /// </summary>
        public IFExtDsgnPoint(long? externalDesignSequence = default(long?), DateTime? externalDesignTimeStamp = default(DateTime?), string operatorId = default(string), string pointNumber = default(string), string pointSpanNumber = default(string), string district = default(string), long? workRequest = default(long?), string workStatusIndicator = default(string), string mainStatusIndicator = default(string), string processIndicator = default(string), string entityCode = default(string), double? spanLength = default(double?), string pointAd = default(string), string pointId = default(string), string crewCode = default(string), string errorFlag = default(string), long? errorRunSequence = default(long?), string contractorCalcInd = default(string), string bidItemCode = default(string), string rWorksFlag = default(string))
        {
            ExternalDesignSequence = externalDesignSequence;
            ExternalDesignTimeStamp = externalDesignTimeStamp;
            OperatorId = operatorId;
            PointNumber = pointNumber;
            PointSpanNumber = pointSpanNumber;
            District = district;
            WorkRequest = workRequest;
            WorkStatusIndicator = workStatusIndicator;
            MainStatusIndicator = mainStatusIndicator;
            ProcessIndicator = processIndicator;
            EntityCode = entityCode;
            SpanLength = spanLength;
            PointAd = pointAd;
            PointId = pointId;
            CrewCode = crewCode;
            ErrorFlag = errorFlag;
            ErrorRunSequence = errorRunSequence;
            ContractorCalcInd = contractorCalcInd;
            BidItemCode = bidItemCode;
            RWorksFlag = rWorksFlag;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalDesignSequence")]
        public long? ExternalDesignSequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalDesignTimeStamp")]
        public DateTime? ExternalDesignTimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpanNumber")]
        public string PointSpanNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequest")]
        public long? WorkRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workStatusIndicator")]
        public string WorkStatusIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainStatusIndicator")]
        public string MainStatusIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "processIndicator")]
        public string ProcessIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entityCode")]
        public string EntityCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spanLength")]
        public double? SpanLength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointAd")]
        public string PointAd { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointId")]
        public string PointId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewCode")]
        public string CrewCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorFlag")]
        public string ErrorFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorRunSequence")]
        public long? ErrorRunSequence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contractorCalcInd")]
        public string ContractorCalcInd { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bidItemCode")]
        public string BidItemCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rWorksFlag")]
        public string RWorksFlag { get; set; }

    }
}
