// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class IFExceptionCond
    {
        /// <summary>
        /// Initializes a new instance of the IFExceptionCond class.
        /// </summary>
        public IFExceptionCond() { }

        /// <summary>
        /// Initializes a new instance of the IFExceptionCond class.
        /// </summary>
        public IFExceptionCond(string cDDIST = default(string), long? cDWR = default(long?), string dSCOND = default(string), string iDOPER = default(string), string fGERROR = default(string), DateTime? tSIFEXCEPTIONCOND = default(DateTime?), long? cDSEQ = default(long?), long? cDSEQERRORRUN = default(long?))
        {
            CDDIST = cDDIST;
            CDWR = cDWR;
            DSCOND = dSCOND;
            IDOPER = iDOPER;
            FGERROR = fGERROR;
            TSIFEXCEPTIONCOND = tSIFEXCEPTIONCOND;
            CDSEQ = cDSEQ;
            CDSEQERRORRUN = cDSEQERRORRUN;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cD_DIST")]
        public string CDDIST { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cD_WR")]
        public long? CDWR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dS_COND")]
        public string DSCOND { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iD_OPER")]
        public string IDOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fG_ERROR")]
        public string FGERROR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tS_IFEXCEPTIONCOND")]
        public DateTime? TSIFEXCEPTIONCOND { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cD_SEQ")]
        public long? CDSEQ { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cD_SEQ_ERROR_RUN")]
        public long? CDSEQERRORRUN { get; set; }

    }
}
