// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class LaborDetail
    {
        /// <summary>
        /// Initializes a new instance of the LaborDetail class.
        /// </summary>
        public LaborDetail() { }

        /// <summary>
        /// Initializes a new instance of the LaborDetail class.
        /// </summary>
        public LaborDetail(string laborCode = default(string), string indOnOff = default(string), string indAction = default(string), string crewClass = default(string), string flagActive = default(string), double? laborHours = default(double?), double? additionalLaborHours = default(double?))
        {
            LaborCode = laborCode;
            IndOnOff = indOnOff;
            IndAction = indAction;
            CrewClass = crewClass;
            FlagActive = flagActive;
            LaborHours = laborHours;
            AdditionalLaborHours = additionalLaborHours;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "laborCode")]
        public string LaborCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indOnOff")]
        public string IndOnOff { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indAction")]
        public string IndAction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewClass")]
        public string CrewClass { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "flagActive")]
        public string FlagActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "laborHours")]
        public double? LaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "additionalLaborHours")]
        public double? AdditionalLaborHours { get; set; }

    }
}
