// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class LeakGeneral
    {
        /// <summary>
        /// Initializes a new instance of the LeakGeneral class.
        /// </summary>
        public LeakGeneral() { }

        /// <summary>
        /// Initializes a new instance of the LeakGeneral class.
        /// </summary>
        public LeakGeneral(long? workRequest = default(long?), long? sequenceCode = default(long?), string leakFoundIndicator = default(string), string leakGradeCode = default(string), string mainValveNumber = default(string))
        {
            WorkRequest = workRequest;
            SequenceCode = sequenceCode;
            LeakFoundIndicator = leakFoundIndicator;
            LeakGradeCode = leakGradeCode;
            MainValveNumber = mainValveNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequest")]
        public long? WorkRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sequenceCode")]
        public long? SequenceCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leakFoundIndicator")]
        public string LeakFoundIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leakGradeCode")]
        public string LeakGradeCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainValveNumber")]
        public string MainValveNumber { get; set; }

    }
}
