// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class MobileRemarkTypes
    {
        /// <summary>
        /// Initializes a new instance of the MobileRemarkTypes class.
        /// </summary>
        public MobileRemarkTypes() { }

        /// <summary>
        /// Initializes a new instance of the MobileRemarkTypes class.
        /// </summary>
        public MobileRemarkTypes(string remarkType = default(string), string operatorId = default(string), DateTime? timeStampLastChanged = default(DateTime?))
        {
            RemarkType = remarkType;
            OperatorId = operatorId;
            TimeStampLastChanged = timeStampLastChanged;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remarkType")]
        public string RemarkType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStampLastChanged")]
        public DateTime? TimeStampLastChanged { get; set; }

    }
}
