// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class MUStructure
    {
        /// <summary>
        /// Initializes a new instance of the MUStructure class.
        /// </summary>
        public MUStructure() { }

        /// <summary>
        /// Initializes a new instance of the MUStructure class.
        /// </summary>
        public MUStructure(string cuCode = default(string), string muCode = default(string), string usage = default(string), double? cuQuantity = default(double?), string drawingSeq = default(string), long? seq = default(long?), long? muStructureProperty = default(long?), string account = default(string), string action = default(string))
        {
            CuCode = cuCode;
            MuCode = muCode;
            Usage = usage;
            CuQuantity = cuQuantity;
            DrawingSeq = drawingSeq;
            Seq = seq;
            MuStructureProperty = muStructureProperty;
            Account = account;
            Action = action;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuCode")]
        public string CuCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "muCode")]
        public string MuCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public string Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuQuantity")]
        public double? CuQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "drawingSeq")]
        public string DrawingSeq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seq")]
        public long? Seq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "muStructure")]
        public long? MuStructureProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public string Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

    }
}
