// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Oper
    {
        /// <summary>
        /// Initializes a new instance of the Oper class.
        /// </summary>
        public Oper() { }

        /// <summary>
        /// Initializes a new instance of the Oper class.
        /// </summary>
        public Oper(string operatorId = default(string), string employeeId = default(string), string company = default(string), string crewHq = default(string), string district = default(string), string division = default(string), string isActive = default(string), string operatorName = default(string), string loginId = default(string), string jobDescription = default(string), string emailId = default(string))
        {
            OperatorId = operatorId;
            EmployeeId = employeeId;
            Company = company;
            CrewHq = crewHq;
            District = district;
            Division = division;
            IsActive = isActive;
            OperatorName = operatorName;
            LoginId = loginId;
            JobDescription = jobDescription;
            EmailId = emailId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employeeId")]
        public string EmployeeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "company")]
        public string Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewHq")]
        public string CrewHq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "division")]
        public string Division { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public string IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorName")]
        public string OperatorName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "loginId")]
        public string LoginId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jobDescription")]
        public string JobDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailId")]
        public string EmailId { get; set; }

    }
}
