// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Phones
    {
        /// <summary>
        /// Initializes a new instance of the Phones class.
        /// </summary>
        public Phones() { }

        /// <summary>
        /// Initializes a new instance of the Phones class.
        /// </summary>
        public Phones(string extension = default(string), string number = default(string), string office = default(string), string cell = default(string), string eMail = default(string))
        {
            Extension = extension;
            Number = number;
            Office = office;
            Cell = cell;
            EMail = eMail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extension")]
        public string Extension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public string Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "office")]
        public string Office { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cell")]
        public string Cell { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eMail")]
        public string EMail { get; set; }

    }
}
