// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class PointAsb
    {
        /// <summary>
        /// Initializes a new instance of the PointAsb class.
        /// </summary>
        public PointAsb() { }

        /// <summary>
        /// Initializes a new instance of the PointAsb class.
        /// </summary>
        public PointAsb(long? workRequestId = default(long?), string pointID = default(string), string pointNumber = default(string), string pointSpanNumber = default(string), string length = default(string), string district = default(string), string mainStatusIndicator = default(string), int? asbuiltDesignNumber = default(int?), DateTime? timeStampLastChanged = default(DateTime?), IList<CUAsb> cuAsbs = default(IList<CUAsb>))
        {
            WorkRequestId = workRequestId;
            PointID = pointID;
            PointNumber = pointNumber;
            PointSpanNumber = pointSpanNumber;
            Length = length;
            District = district;
            MainStatusIndicator = mainStatusIndicator;
            AsbuiltDesignNumber = asbuiltDesignNumber;
            TimeStampLastChanged = timeStampLastChanged;
            CuAsbs = cuAsbs;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointID")]
        public string PointID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpanNumber")]
        public string PointSpanNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "length")]
        public string Length { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainStatusIndicator")]
        public string MainStatusIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asbuiltDesignNumber")]
        public int? AsbuiltDesignNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeStampLastChanged")]
        public DateTime? TimeStampLastChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuAsbs")]
        public IList<CUAsb> CuAsbs { get; set; }

    }
}
