// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Point
    {
        /// <summary>
        /// Initializes a new instance of the Point class.
        /// </summary>
        public Point() { }

        /// <summary>
        /// Initializes a new instance of the Point class.
        /// </summary>
        public Point(string workRequestId = default(string), string designNumber = default(string), string pointId = default(string), string pointNumber = default(string), string pointSpanNumber = default(string), string length = default(string), string district = default(string), string mainStatusIndicator = default(string), string restorationFlag = default(string), IList<CU> cUs = default(IList<CU>))
        {
            WorkRequestId = workRequestId;
            DesignNumber = designNumber;
            PointId = pointId;
            PointNumber = pointNumber;
            PointSpanNumber = pointSpanNumber;
            Length = length;
            District = district;
            MainStatusIndicator = mainStatusIndicator;
            RestorationFlag = restorationFlag;
            CUs = cUs;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public string WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designNumber")]
        public string DesignNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointId")]
        public string PointId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointNumber")]
        public string PointNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pointSpanNumber")]
        public string PointSpanNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "length")]
        public string Length { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mainStatusIndicator")]
        public string MainStatusIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "restorationFlag")]
        public string RestorationFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cUs")]
        public IList<CU> CUs { get; set; }

    }
}
