// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class PremiseMore
    {
        /// <summary>
        /// Initializes a new instance of the PremiseMore class.
        /// </summary>
        public PremiseMore() { }

        /// <summary>
        /// Initializes a new instance of the PremiseMore class.
        /// </summary>
        public PremiseMore(long? workRequestId = default(long?), string district = default(string), string premiseId = default(string), string serviceId = default(string), string numberInHousehold = default(string), string buildingSqFootage = default(string), string heatLoad = default(string), string meterSize = default(string), string furnaceBoilerEfficiency = default(string), string baseLoad = default(string), string insulationPackage = default(string), string deliveryPressure = default(string))
        {
            WorkRequestId = workRequestId;
            District = district;
            PremiseId = premiseId;
            ServiceId = serviceId;
            NumberInHousehold = numberInHousehold;
            BuildingSqFootage = buildingSqFootage;
            HeatLoad = heatLoad;
            MeterSize = meterSize;
            FurnaceBoilerEfficiency = furnaceBoilerEfficiency;
            BaseLoad = baseLoad;
            InsulationPackage = insulationPackage;
            DeliveryPressure = deliveryPressure;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "premiseId")]
        public string PremiseId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberInHousehold")]
        public string NumberInHousehold { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildingSqFootage")]
        public string BuildingSqFootage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "heatLoad")]
        public string HeatLoad { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meterSize")]
        public string MeterSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "furnaceBoilerEfficiency")]
        public string FurnaceBoilerEfficiency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseLoad")]
        public string BaseLoad { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "insulationPackage")]
        public string InsulationPackage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deliveryPressure")]
        public string DeliveryPressure { get; set; }

    }
}
