// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Premise
    {
        /// <summary>
        /// Initializes a new instance of the Premise class.
        /// </summary>
        public Premise() { }

        /// <summary>
        /// Initializes a new instance of the Premise class.
        /// </summary>
        public Premise(string url = default(string), string district = default(string), long? workRequestId = default(long?), string premiseId = default(string), string sic = default(string), string rateClass = default(string), string revenueClass = default(string), long? addressCode = default(long?), string hazardFlag = default(string), string keyAvailFlag = default(string), double? baseLoadQuantity = default(double?), double? heatingFactorQuantity = default(double?), string serviceId = default(string), PremiseMore premiseMore = default(PremiseMore))
        {
            Url = url;
            District = district;
            WorkRequestId = workRequestId;
            PremiseId = premiseId;
            Sic = sic;
            RateClass = rateClass;
            RevenueClass = revenueClass;
            AddressCode = addressCode;
            HazardFlag = hazardFlag;
            KeyAvailFlag = keyAvailFlag;
            BaseLoadQuantity = baseLoadQuantity;
            HeatingFactorQuantity = heatingFactorQuantity;
            ServiceId = serviceId;
            PremiseMore = premiseMore;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "premiseId")]
        public string PremiseId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sic")]
        public string Sic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rateClass")]
        public string RateClass { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revenueClass")]
        public string RevenueClass { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressCode")]
        public long? AddressCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hazardFlag")]
        public string HazardFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keyAvailFlag")]
        public string KeyAvailFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baseLoadQuantity")]
        public double? BaseLoadQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "heatingFactorQuantity")]
        public double? HeatingFactorQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceId")]
        public string ServiceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "premiseMore")]
        public PremiseMore PremiseMore { get; set; }

    }
}
