// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class Remark
    {
        /// <summary>
        /// Initializes a new instance of the Remark class.
        /// </summary>
        public Remark() { }

        /// <summary>
        /// Initializes a new instance of the Remark class.
        /// </summary>
        public Remark(DateTime? creationDate = default(DateTime?), string creatorId = default(string), string district = default(string), string remarkText = default(string), int? seq = default(int?), string type = default(string), string url = default(string), long? workRequestId = default(long?))
        {
            CreationDate = creationDate;
            CreatorId = creatorId;
            District = district;
            RemarkText = remarkText;
            Seq = seq;
            Type = type;
            Url = url;
            WorkRequestId = workRequestId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creationDate")]
        public DateTime? CreationDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "creatorId")]
        public string CreatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remarkText")]
        public string RemarkText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seq")]
        public int? Seq { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

    }
}
