// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class RemarkType
    {
        /// <summary>
        /// Initializes a new instance of the RemarkType class.
        /// </summary>
        public RemarkType() { }

        /// <summary>
        /// Initializes a new instance of the RemarkType class.
        /// </summary>
        public RemarkType(string url = default(string), string type = default(string), string remarkTypeDescription = default(string), string activeFlag = default(string), string interfaceFlag = default(string))
        {
            Url = url;
            Type = type;
            RemarkTypeDescription = remarkTypeDescription;
            ActiveFlag = activeFlag;
            InterfaceFlag = interfaceFlag;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remarkTypeDescription")]
        public string RemarkTypeDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "activeFlag")]
        public string ActiveFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "interfaceFlag")]
        public string InterfaceFlag { get; set; }

    }
}
