// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class UnitDetail
    {
        /// <summary>
        /// Initializes a new instance of the UnitDetail class.
        /// </summary>
        public UnitDetail() { }

        /// <summary>
        /// Initializes a new instance of the UnitDetail class.
        /// </summary>
        public UnitDetail(string url = default(string), string name = default(string), string cuKind = default(string), string cuMake = default(string), string labor = default(string), string uom = default(string), string usage = default(string), string description = default(string), string discontinuedDate = default(string), string effectiveDate = default(string), string laborHours = default(string), string capitalFlag = default(string), string maintenanceFlag = default(string), string operationsFlag = default(string), string restorationFlag = default(string), string temporaryFLag = default(string), string cuMuIndicator = default(string), string util = default(string), string asset = default(string), string cuType = default(string), string spec = default(string), string facilityCode = default(string), string hourChangedFlag = default(string), string lastChangedDateTime = default(string), string materialItemTotalAmount = default(string), string salvageTotalAmount = default(string), string scrapTotalAmount = default(string), string category = default(string), string account = default(string), string action = default(string), string hideCuFlag = default(string), string bidItem = default(string), string mobileFlag = default(string), IList<CUStructure> cuStructures = default(IList<CUStructure>), Facility facility = default(Facility))
        {
            Url = url;
            Name = name;
            CuKind = cuKind;
            CuMake = cuMake;
            Labor = labor;
            Uom = uom;
            Usage = usage;
            Description = description;
            DiscontinuedDate = discontinuedDate;
            EffectiveDate = effectiveDate;
            LaborHours = laborHours;
            CapitalFlag = capitalFlag;
            MaintenanceFlag = maintenanceFlag;
            OperationsFlag = operationsFlag;
            RestorationFlag = restorationFlag;
            TemporaryFLag = temporaryFLag;
            CuMuIndicator = cuMuIndicator;
            Util = util;
            Asset = asset;
            CuType = cuType;
            Spec = spec;
            FacilityCode = facilityCode;
            HourChangedFlag = hourChangedFlag;
            LastChangedDateTime = lastChangedDateTime;
            MaterialItemTotalAmount = materialItemTotalAmount;
            SalvageTotalAmount = salvageTotalAmount;
            ScrapTotalAmount = scrapTotalAmount;
            Category = category;
            Account = account;
            Action = action;
            HideCuFlag = hideCuFlag;
            BidItem = bidItem;
            MobileFlag = mobileFlag;
            CuStructures = cuStructures;
            Facility = facility;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuKind")]
        public string CuKind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuMake")]
        public string CuMake { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "labor")]
        public string Labor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uom")]
        public string Uom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public string Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "discontinuedDate")]
        public string DiscontinuedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectiveDate")]
        public string EffectiveDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "laborHours")]
        public string LaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capitalFlag")]
        public string CapitalFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maintenanceFlag")]
        public string MaintenanceFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operationsFlag")]
        public string OperationsFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "restorationFlag")]
        public string RestorationFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "temporaryFLag")]
        public string TemporaryFLag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuMuIndicator")]
        public string CuMuIndicator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "util")]
        public string Util { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuType")]
        public string CuType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spec")]
        public string Spec { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facilityCode")]
        public string FacilityCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hourChangedFlag")]
        public string HourChangedFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastChangedDateTime")]
        public string LastChangedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "materialItemTotalAmount")]
        public string MaterialItemTotalAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "salvageTotalAmount")]
        public string SalvageTotalAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scrapTotalAmount")]
        public string ScrapTotalAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public string Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hideCuFlag")]
        public string HideCuFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bidItem")]
        public string BidItem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mobileFlag")]
        public string MobileFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuStructures")]
        public IList<CUStructure> CuStructures { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "facility")]
        public Facility Facility { get; set; }

    }
}
