// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class WeTWorkAlloc
    {
        /// <summary>
        /// Initializes a new instance of the WeTWorkAlloc class.
        /// </summary>
        public WeTWorkAlloc() { }

        /// <summary>
        /// Initializes a new instance of the WeTWorkAlloc class.
        /// </summary>
        public WeTWorkAlloc(long? cDWORKPACKET = default(long?), DateTime? dTWORK = default(DateTime?), int? iDCREW = default(int?), long? cDWR = default(long?), DateTime? dTSCHED = default(DateTime?), double? hRALLOC = default(double?), double? hRLBLREM = default(double?), double? hRLBR = default(double?), string fGSENTSTORMS = default(string), string fGDESCHEDULE = default(string), string iDCREWRESCHED = default(string))
        {
            CDWORKPACKET = cDWORKPACKET;
            DTWORK = dTWORK;
            IDCREW = iDCREW;
            CDWR = cDWR;
            DTSCHED = dTSCHED;
            HRALLOC = hRALLOC;
            HRLBLREM = hRLBLREM;
            HRLBR = hRLBR;
            FGSENTSTORMS = fGSENTSTORMS;
            FGDESCHEDULE = fGDESCHEDULE;
            IDCREWRESCHED = iDCREWRESCHED;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cD_WORKPACKET")]
        public long? CDWORKPACKET { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dT_WORK")]
        public DateTime? DTWORK { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iD_CREW")]
        public int? IDCREW { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cD_WR")]
        public long? CDWR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dT_SCHED")]
        public DateTime? DTSCHED { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hR_ALLOC")]
        public double? HRALLOC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hR_LBL_REM")]
        public double? HRLBLREM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hR_LBR")]
        public double? HRLBR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fG_SENTSTORMS")]
        public string FGSENTSTORMS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fG_DESCHEDULE")]
        public string FGDESCHEDULE { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iD_CREWRESCHED")]
        public string IDCREWRESCHED { get; set; }

    }
}
