// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    

    public partial class WorkPacket
    {
        /// <summary>
        /// Initializes a new instance of the WorkPacket class.
        /// </summary>
        public WorkPacket() { }

        /// <summary>
        /// Initializes a new instance of the WorkPacket class.
        /// </summary>
        public WorkPacket(string uri = default(string), string workRequestId = default(string), string workPacketId = default(string), string district = default(string), string name = default(string), string crewClass = default(string), string crew = default(string), string crewCompleted = default(string), double? totalLaborHours = default(double?), double? totalLaborHoursConstruction = default(double?), DateTime? scheduledDate = default(DateTime?), string resolutionCode = default(string), DateTime? completionDate = default(DateTime?), IList<WorkPacketHistory> workPacketHistories = default(IList<WorkPacketHistory>), IList<CU> cus = default(IList<CU>), IList<CUAsb> cuAsbs = default(IList<CUAsb>))
        {
            Uri = uri;
            WorkRequestId = workRequestId;
            WorkPacketId = workPacketId;
            District = district;
            Name = name;
            CrewClass = crewClass;
            Crew = crew;
            CrewCompleted = crewCompleted;
            TotalLaborHours = totalLaborHours;
            TotalLaborHoursConstruction = totalLaborHoursConstruction;
            ScheduledDate = scheduledDate;
            ResolutionCode = resolutionCode;
            CompletionDate = completionDate;
            WorkPacketHistories = workPacketHistories;
            Cus = cus;
            CuAsbs = cuAsbs;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uri")]
        public string Uri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public string WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workPacketId")]
        public string WorkPacketId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewClass")]
        public string CrewClass { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crew")]
        public string Crew { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewCompleted")]
        public string CrewCompleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalLaborHours")]
        public double? TotalLaborHours { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalLaborHoursConstruction")]
        public double? TotalLaborHoursConstruction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scheduledDate")]
        public DateTime? ScheduledDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resolutionCode")]
        public string ResolutionCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "completionDate")]
        public DateTime? CompletionDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workPacketHistories")]
        public IList<WorkPacketHistory> WorkPacketHistories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cus")]
        public IList<CU> Cus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cuAsbs")]
        public IList<CUAsb> CuAsbs { get; set; }

    }
}
