// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.ComponentModel.DataAnnotations;

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class WorkRequest
    {
        /// <summary>
        /// Initializes a new instance of the WorkRequest class.
        /// </summary>
        public WorkRequest() { }

        /// <summary>
        /// Initializes a new instance of the WorkRequest class.
        /// </summary>
        public WorkRequest(string url = default(string), long? id = default(long?), string district = default(string), string workCompletedDate = default(string), string workRequestClosedDate = default(string), string jobDescription = default(string), string requiredDate = default(string), string crewHeadquarter = default(string), string workType = default(string), string jobCode = default(string), string jobType = default(string), string reviewDate = default(string), string suprevisorId = default(string), string project = default(string), string projectName = default(string), string ioInstallation = default(string), string ioRemoval = default(string), string ioTransfer = default(string), string ioRevenue = default(string), string meterNo = default(string), string dateCanceled = default(string), string status = default(string), bool? canceled = default(bool?), string assignedTo = default(string), string priority = default(string), long? workRequestRelatedTo = default(long?), string externalJobNumber = default(string), string externalSystemId = default(string), double? hrEstTime = default(double?), string resolution = default(string), string contactName = default(string), string contactPhone = default(string), Address address = default(Address), Geo geo = default(Geo), string designsUri = default(string), string extraDetailsUri = default(string), string customersUri = default(string), string associatedPartiesUri = default(string), string remarksUri = default(string), string milestoneRequirementsUri = default(string), string premisesUri = default(string), string gasLoadDetailsUri = default(string), string workPacketsUri = default(string), string workRequestTrackingsUri = default(string), string asBuiltUri = default(string), string documentsUri = default(string), string exceptionConditionUri = default(string), string ifMobileCompletionUri = default(string))
        {
            Url = url;
            Id = id;
            District = district;
            WorkCompletedDate = workCompletedDate;
            WorkRequestClosedDate = workRequestClosedDate;
            JobDescription = jobDescription;
            RequiredDate = requiredDate;
            CrewHeadquarter = crewHeadquarter;
            WorkType = workType;
            JobCode = jobCode;
            JobType = jobType;
            ReviewDate = reviewDate;
            SuprevisorId = suprevisorId;
            Project = project;
            ProjectName = projectName;
            IoInstallation = ioInstallation;
            IoRemoval = ioRemoval;
            IoTransfer = ioTransfer;
            IoRevenue = ioRevenue;
            MeterNo = meterNo;
            DateCanceled = dateCanceled;
            Status = status;
            Canceled = canceled;
            AssignedTo = assignedTo;
            Priority = priority;
            WorkRequestRelatedTo = workRequestRelatedTo;
            ExternalJobNumber = externalJobNumber;
            ExternalSystemId = externalSystemId;
            HrEstTime = hrEstTime;
            Resolution = resolution;
            ContactName = contactName;
            ContactPhone = contactPhone;
            Address = address;
            Geo = geo;
            DesignsUri = designsUri;
            ExtraDetailsUri = extraDetailsUri;
            CustomersUri = customersUri;
            AssociatedPartiesUri = associatedPartiesUri;
            RemarksUri = remarksUri;
            MilestoneRequirementsUri = milestoneRequirementsUri;
            PremisesUri = premisesUri;
            GasLoadDetailsUri = gasLoadDetailsUri;
            WorkPacketsUri = workPacketsUri;
            WorkRequestTrackingsUri = workRequestTrackingsUri;
            AsBuiltUri = asBuiltUri;
            DocumentsUri = documentsUri;
            ExceptionConditionUri = exceptionConditionUri;
            IfMobileCompletionUri = ifMobileCompletionUri;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workCompletedDate")]
        public string WorkCompletedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestClosedDate")]
        public string WorkRequestClosedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jobDescription")]
        public string JobDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredDate")]
        public string RequiredDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crewHeadquarter")]
        public string CrewHeadquarter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workType")]
        public string WorkType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jobCode")]
        public string JobCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jobType")]
        public string JobType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reviewDate")]
        public string ReviewDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suprevisorId")]
        public string SuprevisorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public string Project { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ioInstallation")]
        public string IoInstallation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ioRemoval")]
        public string IoRemoval { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ioTransfer")]
        public string IoTransfer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ioRevenue")]
        public string IoRevenue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meterNo")]
        public string MeterNo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateCanceled")]
        public string DateCanceled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "canceled")]
        public bool? Canceled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assignedTo")]
        public string AssignedTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "priority")]
        public string Priority { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestRelatedTo")]
        public long? WorkRequestRelatedTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalJobNumber")]
        public string ExternalJobNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "externalSystemId")]
        public string ExternalSystemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hrEstTime")]
        public double? HrEstTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resolution")]
        public string Resolution { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactName")]
        public string ContactName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactPhone")]
        public string ContactPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public Address Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "geo")]
        public Geo Geo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designsUri")]
        public string DesignsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extraDetailsUri")]
        public string ExtraDetailsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customersUri")]
        public string CustomersUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "associatedPartiesUri")]
        public string AssociatedPartiesUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remarksUri")]
        public string RemarksUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "milestoneRequirementsUri")]
        public string MilestoneRequirementsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "premisesUri")]
        public string PremisesUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gasLoadDetailsUri")]
        public string GasLoadDetailsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workPacketsUri")]
        public string WorkPacketsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestTrackingsUri")]
        public string WorkRequestTrackingsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asBuiltUri")]
        public string AsBuiltUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentsUri")]
        public string DocumentsUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exceptionConditionUri")]
        public string ExceptionConditionUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ifMobileCompletionUri")]
        public string IfMobileCompletionUri { get; set; }

    }
}
