// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class WorkType
    {
        /// <summary>
        /// Initializes a new instance of the WorkType class.
        /// </summary>
        public WorkType() { }

        /// <summary>
        /// Initializes a new instance of the WorkType class.
        /// </summary>
        public WorkType(string url = default(string), string id = default(string), string description = default(string))
        {
            Url = url;
            Id = id;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
