// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class WRTracking
    {
        /// <summary>
        /// Initializes a new instance of the WRTracking class.
        /// </summary>
        public WRTracking() { }

        /// <summary>
        /// Initializes a new instance of the WRTracking class.
        /// </summary>
        public WRTracking(string url = default(string), string district = default(string), string status = default(string), long? workRequestId = default(long?), string operatorId = default(string), string function = default(string), string typeOfChange = default(string), DateTime? changeDate = default(DateTime?), long? id = default(long?))
        {
            Url = url;
            District = district;
            Status = status;
            WorkRequestId = workRequestId;
            OperatorId = operatorId;
            Function = function;
            TypeOfChange = typeOfChange;
            ChangeDate = changeDate;
            Id = id;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "district")]
        public string District { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "workRequestId")]
        public long? WorkRequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorId")]
        public string OperatorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "function")]
        public string Function { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeOfChange")]
        public string TypeOfChange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "changeDate")]
        public DateTime? ChangeDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

    }
}
