// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Forestry.Models.ManagedWorkOrder
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Zone
    {
        /// <summary>
        /// Initializes a new instance of the Zone class.
        /// </summary>
        public Zone() { }

        /// <summary>
        /// Initializes a new instance of the Zone class.
        /// </summary>
        public Zone(string url = default(string), string name = default(string), string description = default(string), string districtId = default(string), string areaId = default(string))
        {
            Url = url;
            Name = name;
            Description = description;
            DistrictId = districtId;
            AreaId = areaId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "districtId")]
        public string DistrictId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "areaId")]
        public string AreaId { get; set; }

    }
}
